### ISSUE TITLE
Max distance?

### ISSUE THREAD

**Issue by lucbettaieb** [neobotix/neo_usboard#4]
Hey,

Seems the usboard is only giving a max distance of 2.5ish meters when the bosch ultrasonics can support up to 5.1.  Is this a firmware limitation?  Looks like some message might be getting capped at 8 bits.

Thanks,
Luc

**Comment by neoflv** [comment]
Hey Luc,
According to the datasheet the USS4 have a "possible" range of 2.5 - 3 m. In reality the usable range is between 0.15 m and 1.5 m. Objects below the minimum create unstable or wrong readings, objects beyond the maximum are in most cases not detected at all.

**Comment by lucbettaieb** [comment]
The Bosch datasheet here says otherwise: https://www.bosch-mobility-solutions.com/media/global/products-and-services/passenger-cars-and-light-commercial-vehicles/driver-assistance-systems/construction-zone-assist/product-data-sheet-ultrasonic-sensors-generation-6.pdf

@neoflv

**Comment by neoflv** [comment]
That is because it is the datasheet for the USS5. The current USBoard only supports USS4.

**Comment by lucbettaieb** [comment]
Hi @neoflv ,

Thanks for the clarification.  However, it looks like we have a different sensor that we got from AutonomouStuff.

We have the Bosch sensor that looks like the middle one in the PDF I gave you.  On the box, it says:

1 St/Pc
0263009525
-850

Would you be able to tell me which one this is?

**Comment by neoflv** [comment]
Hi Luc,
That is the default version of the USS4 with radial connector. The new USS5 uses the same housing to make switching easier. This also makes things a bit confusing.

**Comment by lucbettaieb** [comment]
@neoflv Thanks so much for the info!  I appreciate it.
