### ISSUE TITLE
Field of View 

### ISSUE THREAD

**Issue by jokla** [neobotix/neo_usboard#5]
Hi!

I am trying to understand the field of view of my ultrasonic sensors. I have the model Bosch Parkpilot 0 263 009 525. I cannot find the datasheet online.

[Here](https://www.neobotix-robots.com/fileadmin/files/downloads/Anleitungen/USBoard-OperatingManual.pdf), at pag 3, it is written: Field of view: 120° x 60°. While in the ROS message the field of view is 60° (+/-30°).

I suppose the base of the cone is elliptical but I am not sure about the horizontal and vertical FOV.

Do you have more information about that?

Thank you in advance!

**Comment by Osiron007** [comment]
Hi Giovanni,

if you mount the sensor as shown in the manual, its 120° for horizontal and 60° for vertical.
We choose to implement the smaller value within our ROS-Node, because http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Range.html only allows one float value.

**Comment by jokla** [comment]
Hi @Osiron007,

Thank you very much for the clarification. 
Is there a way to reduce the horizontal FOV?
Or to retrieve the angle of the object detected?

Last question, which other sensors are compatible with your board? 

I would need a smaller horizontal field of view, if I invert the axis, the sensor would easily detect the ground probably.

**Comment by Osiron007** [comment]
Hi Giovanni,

the board is only compatible with the sensor you are using. Unfortunately there is no way to reduce the FOV.

**Comment by jokla** [comment]
OK, thank you very much for your answer.

**Comment by AlexisTM** [comment]
@jokla You can use a sound reflective surface to reduce the FoV (such as aluminium)
