### ISSUE TITLE
Limitations in the use compared to the declarations in the data sheet

### ISSUE THREAD

**Issue by christinaionescu** [neobotix/neo_usboard#7]
Hi everyone,

I am currently testing the Bosch US Sensors using the neobotix board. Reading the data works fine but I have a few questions regarding the limitations:

1. In the Wiki it is stated that the rate for reading the sensor data is limited to 5Hz which is very slow, is this correct? What does the usboard_timeout mean?

2. As already confirmed in another issue, the possible range is in reality (0.15-1.5m) smaller than declared in the data sheet (0.15-2.5m). Furthermore, objects positioned closer than 0,15m produce false sensor values which is especially problematic. Is there any workaround?

3. I tested the field of view/opening angle and I achieve varying angles depending on the distance. In the mean I achieve an angle around +/- 40 degrees in the horizontal direction while in the vertical direction I achieve an angle of around +/- 30 degrees. Here, the data sheet declares angles of +/- 60 and 30 degrees. Can you confirm these deviating observations?

Thank you so much!
Best regards
Christina

**Comment by neoflv** [comment]
Hi Christina,

1. For the old USBoard that is the minimum setting for automatic sending. You can poll much faster, though. I will ask a colleague to explain usboard_timeout.

2. Not for the USS4 sensors, sorry. We did solve this problem with the USS5 in our USBoardUSS5 (https://docs.neobotix.de/display/USBoardUSS5/Commands+-+Befehle#Commands-Befehle-CMD_GET_DATA), which will be available in a few weeks.

3. The Bosch datasheet states the maximum theoretical FOV. In reality we also found that the angles are smaller. This also depends on the shape, size and material of the object. We are in the middle of making a detailled test with the USS5 to map the actual FOV for different objects. I will upload the result to our onlince documentation as soon as they are available.

Best regards,
Florian

**Comment by christinaionescu** [comment]
Hi Florian,

thank you so much for this fast and helpful reply!

To confirm that I understood everything correctly:

1. So the declaration of "(5Hz maximum)" in the documentation for the request rate: "Request and Publish rate of sensor values in [Hz] (5Hz maximum)" can be ignored?

2. Ok!

3. That would be very helpful. Do you have an approximate time frame when the results of the FOV will be published?

Thank you!
Best regards
Christina

**Comment by neoflv** [comment]
Hi Christina,

No problem!

1. Kind of. It should be "Publish rate ..." only. Requests can come in faster but might yield partially old data if the USBoard has not yet finished its full measurement cycle. It is recommended to deactivate unused sensors to speed up the actual measurement update rate.

3. I was about to go to the workshop and start the test when I saw your message. Should be done next week.

Best regards,
Florian

**Comment by madMAx43v3r** [comment]
"usboard_timeout" defines when the board is considered as disconnected, if for this amount of time no data has been received. However the parameter is actually called "message_timeout", but in any case I don't think it matters for your case.

**Comment by christinaionescu** [comment]
Thank you! :) 
I am looking forward to your test results.
One final question: the issue of false values if an object closer than 15cm is detected: is this a problem resulting from the sensor itself or from the USBoard?

Best regards
Christina

**Comment by neoflv** [comment]
The first test results are online: https://docs.neobotix.de/display/USBoardUSS5/USS5+Field+of+View+-+USS5+Erfassungsbereich
Of course we will continue testing and uploading in the next weeks, but it is a rather tedious process.

I am not sure if the problem with the USS4 at short distances is caused by the sensors. Their protocol differs from the USS5's. The USS5 allow a pretty clear identification of the different cases.

Best regards,
Florian

**Comment by christinaionescu** [comment]
Hi Florian,

thank you very much for the supply of your measurement data.
Can you tell me how the sensor USS5 behaves below the minimum range of 15cm? With the USS4 I detected several measurement points with an angle of 40 degree (vertical) and 75 degree (horizontal). This makes the use of the USS4 too risky as in our case they are mounted a few centimeters inside the vehicle and therefore might detect the vehicle itself. If you can exclude the possibility of measurement points below 15cm except right in front of the sensor the USS5 sensors and board could be a good option for our application.

Best regards

--
Christina Ionescu, M. Sc.
Research Assistant: Mobile Robotics

Faculty for Mechanical Engineering
Cybernetics Lab IMA& IfU
RWTH Aachen University
Dennewartstr. 27
52068 Aachen, Germany
christina.ionescu@ifu.rwth-aachen.de<mailto:christina.ionescu@ifu.rwth-aachen.de>
www.cybernetics-lab.de<http://www.cybernetics-lab.de/>

Von: neoflv <notifications@github.com>
Gesendet: Freitag, 13. November 2020 10:11
An: neobotix/neo_usboard <neo_usboard@noreply.github.com>
Cc: Ionescu, Christina <christina.ionescu@ifu.rwth-aachen.de>; Author <author@noreply.github.com>
Betreff: Re: [neobotix/neo_usboard] Limitations in the use compared to the declarations in the data sheet (#7)


The first test results are online: https://docs.neobotix.de/display/USBoardUSS5/USS5+Field+of+View+-+USS5+Erfassungsbereich
Of course we will continue testing and uploading in the next weeks, but it is a rather tedious process.

I am not sure if the problem with the USS4 at short distances is caused by the sensors. Their protocol differs from the USS5's. The USS5 allow a pretty clear identification of the different cases.

Best regards,
Florian

**Comment by neoflv** [comment]
Hi Christina,

We have added some more measurements in vertical orientation with the USS5.
I am afraid you will have to do some experiments in your actual setup to know the effects for sure. Different from the USS4 the USS5 will output an error if an obstacle is detected closer than the minimum range. Only in very rare edge cases the echo will still be interpreted as valid measurement. It will depend on your mounting situation if the USS5 can shoot through the gap and produce reasonable data or will simply say "blocked" permanently.
We have a few USBoardUSS5 available for testing right now. Would you like to try it out for a few weeks?

Best regards,

Florian

**Comment by christinaionescu** [comment]
Hi Florian,

that would be great! I would like to do that.

Best regards

--
Christina Ionescu, M. Sc.
Research Assistant: Mobile Robotics

Faculty for Mechanical Engineering
Cybernetics Lab IMA& IfU
RWTH Aachen University
Dennewartstr. 27
52068 Aachen, Germany
christina.ionescu@ifu.rwth-aachen.de<mailto:christina.ionescu@ifu.rwth-aachen.de>
www.cybernetics-lab.de<http://www.cybernetics-lab.de/>

Von: neoflv <notifications@github.com>
Gesendet: Montag, 23. November 2020 10:04
An: neobotix/neo_usboard <neo_usboard@noreply.github.com>
Cc: Ionescu, Christina <christina.ionescu@ifu.rwth-aachen.de>; Author <author@noreply.github.com>
Betreff: Re: [neobotix/neo_usboard] Limitations in the use compared to the declarations in the data sheet (#7)


Hi Christina,

We have added some more measurements in vertical orientation with the USS5.
I am afraid you will have to do some experiments in your actual setup to know the effects for sure. Different from the USS4 the USS5 will output an error if an obstacle is detected closer than the minimum range. Only in very rare edge cases the echo will still be interpreted as valid measurement. It will depend on your mounting situation if the USS5 can shoot through the gap and produce reasonable data or will simply say "blocked" permanently.
We have a few USBoardUSS5 available for testing right now. Would you like to try it out for a few weeks?

Best regards,

Florian
