### ISSUE TITLE
Foxy devel

### ISSUE THREAD

**Issue by TJHBlandon** [neobotix/neo_usboard#8]
Hi,
May i know if there's a ros2 package for the neo_usboard.

Thank you.

**Comment by padhupradheep** [comment]
Hey,

Unfortunately we do not have plans in our roadmap for the development of ROS-2 node for this particular version of USBoard. But, if you are interested, we have a new generation of these boards called as USBoardUSS5, which also has support for ROS-2. Please feel free to checkout for more details here: https://www.neobotix-robots.com/products/robot-components/usboarduss5
